// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: classifier.proto

package integration

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Classifier_ClassifyEmail_FullMethodName = "/classifier.Classifier/ClassifyEmail"
)

// ClassifierClient is the client API for Classifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassifierClient interface {
	ClassifyEmail(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
}

type classifierClient struct {
	cc grpc.ClientConnInterface
}

func NewClassifierClient(cc grpc.ClientConnInterface) ClassifierClient {
	return &classifierClient{cc}
}

func (c *classifierClient) ClassifyEmail(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, Classifier_ClassifyEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassifierServer is the server API for Classifier service.
// All implementations must embed UnimplementedClassifierServer
// for forward compatibility
type ClassifierServer interface {
	ClassifyEmail(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	mustEmbedUnimplementedClassifierServer()
}

// UnimplementedClassifierServer must be embedded to have forward compatible implementations.
type UnimplementedClassifierServer struct {
}

func (UnimplementedClassifierServer) ClassifyEmail(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyEmail not implemented")
}
func (UnimplementedClassifierServer) mustEmbedUnimplementedClassifierServer() {}

// UnsafeClassifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassifierServer will
// result in compilation errors.
type UnsafeClassifierServer interface {
	mustEmbedUnimplementedClassifierServer()
}

func RegisterClassifierServer(s grpc.ServiceRegistrar, srv ClassifierServer) {
	s.RegisterService(&Classifier_ServiceDesc, srv)
}

func _Classifier_ClassifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServer).ClassifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Classifier_ClassifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServer).ClassifyEmail(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Classifier_ServiceDesc is the grpc.ServiceDesc for Classifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Classifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "classifier.Classifier",
	HandlerType: (*ClassifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyEmail",
			Handler:    _Classifier_ClassifyEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classifier.proto",
}
