# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63lassifier.proto\x12\nclassifier\"%\n\x0f\x43lassifyRequest\x12\x12\n\nemail_text\x18\x01 \x01(\t\"(\n\x10\x43lassifyResponse\x12\x14\n\x0cis_rejection\x18\x01 \x01(\x08\x32X\n\nClassifier\x12J\n\rClassifyEmail\x12\x1b.classifier.ClassifyRequest\x1a\x1c.classifier.ClassifyResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classifier_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLASSIFYREQUEST._serialized_start=32
  _CLASSIFYREQUEST._serialized_end=69
  _CLASSIFYRESPONSE._serialized_start=71
  _CLASSIFYRESPONSE._serialized_end=111
  _CLASSIFIER._serialized_start=113
  _CLASSIFIER._serialized_end=201
# @@protoc_insertion_point(module_scope)
